src/App.js
Support input and validation for arxiv style pids (modern style - 2007onwards)
=> PIDMR-26 Support and validate arxiv pids

src/App.js
Add support for accepting and validating software heritage pids
=> PIDMR-25 Support swh pids

src/App.js
Use api to provide the list of supported types for pids (instead of static view)
=> PIDMR-43 use the api to display supported pids view

src/App.js
Use api for resolving pids in a single way
=> PIDMR-44 UI makes use of api for resolving

src/Jenkinsfile
Add jenkinsfile that builds pidmr
=> PIDMR-20 Automate ui build and deploy

src/App.js
landingPage, metadata, resource options should be under pidMode url parameter
=> PIDMR-48 pidmir-ui: fix pidMode parameter when calling backend api

src/App.tsx
Use backend api for identifying pids
Use backend identify response for 
- providing info on pid type and if its valid or not
- providing example
- enabling/disabling resolution buttons based on available resolution modes
- fix minor bug in supported pid page (combo box didn't update correctly when changed page size)
=> PIDMR-88 Use backend for identify pid

src/App.tsx
Resolve buttons should be enabled only when a user entered a valid pid
=> PIDMR-91 Enable resolve buttons when pid is valid

package-lock.json, package.json, src/AdminPanel.tsx, src/App.tsx, src/Navigation.tsx, src/auth/AuthContext.tsx, src/auth/KeycloakLogout.tsx, src/auth/ProtectedRoute.tsx, src/auth/index.ts, src/keycloak.json, src/main.tsx
Add keycloak-js dependency
Add context component to handle keycloak information
Add Protected route component to enforce keycloak login
Add Logout component
Add Navigation component
Add Admin View placeholder component
=> PIDMR-100 Add keycloak integration

.env, package-lock.json, package.json, src/AddEditProvider.tsx, src/AdminPanel.tsx, src/App.tsx, src/DeleteModal.tsx, src/Navigation.tsx, src/SupportedPids.tsx, src/auth/AuthContext.tsx, src/auth/ProtectedRoute.tsx, src/types.ts
Give the ability to a user logged in with the admin role to add, edit and delete providers
First of all the application needs to know the keycloak service name of the backend api service. This is given as an environment variable named `VITE_PIDMR_API_KEYCLOAK_SERVICE_NAME` and defaults to `backend-service` which is used in the local keycloak environment in pidmr api
Update `ProtectedRoute` component during keycloak loggin handling to check if user has admin role in the resource access list for the pidmr api backend service _(uses env variable mentioned before)_
Move code that is used to display the Supported PIDs list into a new component named: `SupportedPids`
Update routing in `App` component accordingly. The list now examines if the user is logged in as an administrator and if so …
=> PIDMR-102 Add/Edit/Delete provider

CHANGELOG.md, package-lock.json, package.json, src/App.css, src/App.tsx, src/Footer.tsx
=> prepare v1.0.0

src/ManagedPids.tsx
Report the correct user id that has created the item instead of reporting the current user id
=> PIDMR-137 Fix created by field in managed pids

CHANGELOG.md, package.json
=> prepare v1.1.0

src/UserRoleRequests.tsx
=> [PIDMR-171] - Change promote user role requestDevel

src/Navigation.tsx, src/UserRole.tsx
=> [PIDMR-167] - Create registration form

src/UserRoleRequests.tsx
Added search by identifier in the UserRoleRequests table.
=> [PIDMR-171] - Implement Admin Users Request Role Change API Endpoint in UI

src/UsersTable.tsx
FIxed bugs and changed the layout of UsersTable.tsx.
=> [PIDMR-170] - Implement Admin User Retrieval API Endpoint in UI

src/ManagedPids.tsx
Changed the word providers to types.
=> [PIDMR-179] - Change list of providers to table layout

src/App.tsx, src/Navigation.tsx, src/UserRoleGuide.tsx
Created a static page with instructions on how someone can become a provider admin.
=> [PIDMR-184] - A static with the steps for providers

src/AddEditProvider.tsx, src/types.ts
=> [PIDMR-186] - Action buttons on top of view page

src/ManagedPids.tsx
…le so that it presents the pending providers first.
=> [PIDMR-187] - Actions in managed pid lists 

src/AddEditProvider.tsx, src/types.ts
API pull request #97 needs to be merged at the same time.
=> [PIDMR-182] - Multiple endpoints in the Provider model

src/SupportedPids.tsx
Fixes pagination issue (Wrong page number `NaN` see here: https://github.com/FC4E-WP5/fc4eosc-PIDMR-ui/issues/59) in supported pids view
=> PIDMR-193 Fix pagination issue in supported pids

CHANGELOG.md, package-lock.json, package.json
=> Prep v1.3.0

src/AddEditProvider.tsx, src/App.tsx, src/InfoText.tsx, src/types.ts
=> PIDMR-277 Update ui to handle the new provider schema

src/AddEditProvider.tsx
=> Fix add example button label

CHANGELOG.md, package-lock.json, package.json, style_script
=> bump v1.4.0

CHANGELOG.md, package-lock.json, package.json, src/AddEditProvider.tsx, src/App.tsx, src/InfoText.tsx, src/SupportedPids.tsx, src/types.ts, style_script
- PIDMR-277 Update ui to handle the new provider schema
=> Version 1.4.0
